name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: info
      run: |
        d=${{secrets.NUGET_SERVER_TOKEN}}
        f=erty
        echo $d
        echo $f
        echo "my_string_$d_$f_."
